version: 2

references:
  docker_container_of_node_browsers: &docker_container_of_node_browsers
    docker:
      - image: circleci/node:6.10.3-browsers
        environment:
          NPM_CONFIG_LOGLEVEL: warn
          TERM: xterm-color
          TZ: /usr/share/zoneinfo/Asia/Tokyo
    working_directory: /tmp/work
    parallelism: 1

jobs:
  job1:
    <<: *docker_container_of_node_browsers
    steps:
      - run:
          name: Install node modules
          command: echo job1
  job2:
    <<: *docker_container_of_node_browsers
    steps:
      - run:
          name: Install node modules
          command: echo job2
  job3:
    <<: *docker_container_of_node_browsers
    steps:
      - run:
          name: Install node modules
          command: echo job2


workflows:
  version: 2
  commit_workflow:
    jobs:
      - job1
      - job2:
          requires:
            - job1
      - job3:
          requires:
            - job1
  nightly_workflow:
    triggers:
      - schedule:
          cron: "*/5 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - job1
      - job2:
          requires:
            - job1
